#!/bin/bash
# 模拟目录切换行为演示

echo "🎯 AI Novel Factory - 插件安装与项目切换演示"
echo "================================================"
echo ""

echo "📦 第一部分：插件安装（只需一次）"
echo "--------------------------------------"
echo ""

echo "步骤1：安装 OpenCode 插件"
echo "命令：npm install -g opencode-ai-novel-factory"
echo ""
echo "结果：✅ 插件安装到全局目录"
echo "位置：$(npm root -g)"
echo ""
echo "插件文件结构："
echo "$(npm root -g)/opencode-ai-novel-factory/"
echo "├── dist/              # 插件代码"
echo "├── agents/            # AI agents"
echo "└── skills/            # AI skills"
echo ""
echo "⚡  重要：此步骤只需执行一次！"
echo ""

echo "⚙️ 第二部分：配置 opencode.json（只需一次）"
echo "--------------------------------------"
echo ""

echo "配置方式1：全局配置（推荐）"
echo "位置：~/.opencode/opencode.json"
echo "内容："
echo '{'
echo '  "plugin": ["opencode-ai-novel-factory"]'
echo '}'
echo ""
echo "✅ 优点：配置一次，所有项目都能用"
echo ""

echo "⚡ 重要：此步骤只需执行一次！"
echo ""

echo "🏭 第三部分：小说项目初始化（每个项目一次）"
echo "--------------------------------------"
echo ""

echo "创建小说项目 A："
echo "目录：~/novels/玄幻-修仙之旅"
echo "命令：请帮我初始化小说工厂项目"
echo ""
echo "结果："
echo "~/novels/玄幻-修仙之旅/"
echo "├── studio/"
echo "│   ├── agents/"
echo "│   ├── automation/"
echo "│   ├── memory/"
echo "│   ├── story/"
echo "│   ├── characters/"
echo "│   ├── style/"
echo "│   └── production/"
echo "└── opencode.json  (可选项目级配置)"
echo ""
echo "✅ 插立完成！可以开始写作：@daily_pipeline"
echo ""

echo "创建小说项目 B："
echo "目录：~/novels/都市-职场奋斗"
echo "命令：请帮我初始化小说工厂项目"
echo ""
echo "结果："
echo "~/novels/都市-职场奋斗/"
echo "├── studio/"
echo "│   └── ... (同项目A)"
echo "└── opencode.json  (可选项目级配置)"
echo ""
echo "✅ 插立完成！可以开始写作：@daily_pipeline"
echo ""

echo "🔄 第四部分：目录切换演示"
echo "--------------------------------------"
echo ""

echo "场景1：切换到已有项目"
echo "命令：cd ~/novels/玄幻-修仙之旅"
echo ""
echo "结果："
echo "✅ 插件自动可用（全局安装）"
echo "✅ 项目设定自动加载（studio/存在）"
echo "✅ 直接开始写作：@daily_pipeline"
echo ""

echo "场景2：切换到新目录"
echo "命令：cd ~/workspace/new-novel"
echo ""
echo "结果："
echo "✅ 插件自动可用（全局安装）"
echo "❌ 需要初始化新项目：请帮我初始化小说工厂项目"
echo ""

echo "场景3：换新电脑"
echo "命令：在新电脑上打开终端"
echo ""
echo "需要执行的步骤："
echo "1. 安装 Node.js (如果未安装)"
echo "2. 安装插件：npm install -g opencode-ai-novel-factory"
echo "3. 配置 opencode.json：运行 setup-opencode.sh"
echo "4. 复制小说项目：从旧电脑复制 studio/ 目录"
echo "5. 开始写作：@daily_pipeline"
echo ""

echo "📊 总结对比表"
echo "--------------------------------------"
echo ""
echo "操作类型            | 需要执行次数 | 影响范围"
echo "--------------------|--------------|----------"
echo "安装 npm 插件       | 1次          | 全局所有项目"
echo "配置 opencode.json  | 1次          | 全局或单项目"
echo "初始化小说项目     | 每个项目1次  | 单个项目"
echo "切换项目目录       | 无限次       | 即时生效"
echo ""
echo "💡 关键理解："
echo "- 插件是全局的，像工具一样，安装一次就能用"
echo "- 项目是独立的，像文件一样，每个小说项目需要一份"
echo "- 切换项目就像打开不同的文件夹，无缝切换"
echo ""

echo "🎯 实际使用示例"
echo "--------------------------------------"
echo ""
echo "早上写玄幻小说："
echo "cd ~/novels/玄幻-修仙之旅"
echo "在OpenCode中：请帮我写下一章"
echo ""
echo "下午写都市小说："
echo "cd ~/novels/都市-职场奋斗"
echo "在OpenCode中：请帮我写下一章"
echo ""
echo "晚上换新电脑："
echo "1. npm install -g opencode-ai-novel-factory"
echo "2. 复制小说项目到新电脑"
echo "3. cd ~/novels/玄幻-修仙之旅"
echo "4. 在OpenCode中：请帮我写下一章"
echo ""
echo "✅ 所有操作都无需重新安装插件！"